### ISSUE TITLE
Uploading zip files sometimes fails

### ISSUE THREAD

**Issue by amedina** [rtCamp/web-stories-wp#505]
Trying to upload a zip file previously generated by the tool sometimes seems to loop forever. 

_Do not alter or remove anything below. The following sections will be managed by moderators only._

**Comment by raovs** [comment]
A few things worth testing:

- A zip file generated by the tool (didn't work when I tested it last)
- An example zip file from the Story ad examples (https://amp.dev/documentation/templates/?format=story_ads tap on Story ads)

**Comment by sayedtaqui** [comment]
@raovs 

- Can you please try to test it now, and share the zip file generated by the tool here in case it doesn't work for you.
- Only the zip file generated by the ad creation tool can be imported into the editor because the import is possible with its own `config.json` file and related assets. The tool is not capable of directly importing HTML bundled in the zip file.

**Comment by raovs** [comment]
This worked great! @calebcordry I don't think we can do generic Story ad zips, but this upload / edit / redownload flow will be very helpful.

**Comment by sayedtaqui** [comment]
Closing as this was resolved. Please reopen if the issue persists.
